name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ghc: ['8.8.4']
        node:
          - 20

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install mops
        run: npm install -g ic-mops

      - name: Install DFX
        uses: dfinity/setup-dfx@main
      
      - name: Start dfx
        run: dfx start --background --clean --host 127.0.0.1:4943

      - name: Deploy canister
        run: dfx deploy test

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Clean Up
        run: killall dfx replica

  aggregate:
    name: e2e:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
